version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl:ro  # 掛載 SSL 憑證目錄
    depends_on:
      - frontend
      - strapi
    restart: unless-stopped
    networks:
      - barn-network

  frontend:
    build:
      context: ./website
      dockerfile: Dockerfile
    expose:
      - "3000"
    depends_on:
      - strapi
    restart: unless-stopped
    environment:
      - NUXT_PUBLIC_STRAPI_URL=http://api.your-domain.com
    networks:
      - barn-network

  strapi:
    build:
      context: ./strapi-backend
      dockerfile: Dockerfile
    expose:
      - "1337"
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - NODE_ENV=production
    volumes:
      - ./strapi-backend/public/uploads:/opt/app/public/uploads
    networks:
      - barn-network

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=strapi
      - POSTGRES_USER=strapi
      - POSTGRES_PASSWORD=strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - barn-network

networks:
  barn-network:
    driver: bridge

volumes:
  postgres-data: